export const AdminPermissions = {
  auditLog: {
    list: ['owner', 'assistant'],
  },
  dashboard: ['owner', 'assistant'],
  settings: {
    read: ['owner'],
    update: ['owner'],
  },
  invites: {
    create: ['owner'],
  },
  exports: {
    data: ['owner', 'assistant'],
  },
  services: {
    updatePrice: ['owner'],
  },
  analytics: {
    bookingFunnel: ['owner', 'assistant'],
    telegramFunnel: ['owner', 'assistant'],
    interactiveFunnel: ['owner', 'assistant'],
    noShow: ['owner', 'assistant'],
  },
  schedule: {
    listSlots: ['owner', 'assistant'],
    listAppointments: ['owner', 'assistant'],
    createSlots: ['owner', 'assistant'],
    createExceptions: ['owner', 'assistant'],
    createBuffers: ['owner', 'assistant'],
    updateSlot: ['owner', 'assistant'],
    deleteSlots: ['owner', 'assistant'],
    getSettings: ['owner', 'assistant'],
    updateSettings: ['owner'],
    cancelAppointment: ['owner', 'assistant'],
    recordOutcome: ['owner', 'assistant'],
  },
  leads: {
    list: ['owner', 'assistant'],
    get: ['owner', 'assistant'],
    updateStatus: ['owner', 'assistant'],
    addNote: ['owner', 'assistant'],
  },
  moderation: {
    list: ['owner', 'assistant'],
    get: ['owner', 'assistant'],
    approve: ['owner', 'assistant'],
    reject: ['owner', 'assistant'],
    escalate: ['owner', 'assistant'],
    answer: ['owner'],
    templates: ['owner', 'assistant'],
    metrics: ['owner', 'assistant'],
  },
  content: {
    list: ['owner', 'editor'],
    get: ['owner', 'editor'],
    create: ['owner', 'editor'],
    update: ['owner', 'editor'],
    publish: ['owner', 'editor'],
    archive: ['owner', 'editor'],
    revisions: ['owner', 'editor'],
    rollback: ['owner', 'editor'],
  },
  interactive: {
    list: ['owner', 'editor'],
    get: ['owner', 'editor'],
    update: ['owner', 'editor'],
    publish: ['owner', 'editor'],
    publishDraft: ['owner', 'editor'],
  },
  glossary: {
    list: ['owner', 'editor'],
    get: ['owner', 'editor'],
    upsert: ['owner', 'editor'],
    publish: ['owner', 'editor'],
    delete: ['owner', 'editor'],
  },
  curated: {
    list: ['owner', 'editor'],
    get: ['owner', 'editor'],
    upsert: ['owner', 'editor'],
    publish: ['owner', 'editor'],
    reorder: ['owner', 'editor'],
  },
  media: {
    list: ['owner', 'editor'],
    upload: ['owner', 'editor'],
    update: ['owner', 'editor'],
    delete: ['owner', 'editor'],
  },
  googleCalendar: {
    connectStart: ['owner'],
    connectCallback: ['owner'],
    sync: ['owner'],
    status: ['owner'],
  },
};
