# Generated by Django 4.2.27 on 2026-01-27 07:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('persistence', '0002_initial_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeFormModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.UUIDField(db_index=True, unique=True)),
                ('payload_encrypted', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intake_forms',
            },
        ),
        migrations.CreateModel(
            name='OutcomeRecordModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.UUIDField(db_index=True, unique=True)),
                ('outcome_data', models.JSONField(default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'outcome_records',
            },
        ),
        # RoleModel, UserModel, UserRoleModel, ConsentModel, AuditLogModel уже созданы в 0001_initial
        # Не создаем их повторно
        migrations.CreateModel(
            name='WaitlistRequestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_id', models.UUIDField(db_index=True)),
                ('client_user_id', models.UUIDField(db_index=True, null=True)),
                ('lead_id', models.UUIDField(blank=True, null=True)),
                ('preferred_time_slots', models.JSONField(default=list)),
                ('preferred_format', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('fulfilled_appointment_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'waitlist_requests',
                'indexes': [models.Index(fields=['service_id', 'status'], name='waitlist_re_service_fccf0e_idx'), models.Index(fields=['client_user_id', 'status'], name='waitlist_re_client__4012d4_idx')],
            },
        ),
        # UserRoleModel уже создан в 0001_initial
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('supported_formats', models.JSONField(default=list)),
                ('duration_minutes', models.IntegerField()),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_currency', models.CharField(default='RUB', max_length=3)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cancel_free_hours', models.IntegerField(blank=True, null=True)),
                ('cancel_partial_hours', models.IntegerField(blank=True, null=True)),
                ('reschedule_min_hours', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services',
                'indexes': [models.Index(fields=['slug'], name='services_slug_ffd546_idx'), models.Index(fields=['status'], name='services_status_6676e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('provider_id', models.CharField(default='yookassa', max_length=50)),
                ('provider_payment_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=50)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['appointment_id'], name='payments_appoint_6bbf4d_idx'), models.Index(fields=['provider_id', 'provider_payment_id'], name='payments_provide_9c622b_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('question', 'Question'), ('review', 'Review'), ('comment', 'Comment')], max_length=50)),
                ('content_encrypted', models.TextField()),
                ('author_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], db_index=True, default='pending', max_length=20)),
                ('trigger_flags', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('answer_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'moderation_items',
                'indexes': [models.Index(fields=['content_type', 'status'], name='moderation__content_a92762_idx'), models.Index(fields=['author_id', 'status'], name='moderation__author__d5e1d6_idx'), models.Index(fields=['status', 'created_at'], name='moderation__status_4d7e38_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_data', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram'), ('referral', 'Referral'), ('organic', 'Organic')], max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], db_index=True, default='new', max_length=20)),
                ('utm_params', models.JSONField(blank=True, null=True)),
                ('timeline_events', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leads',
                'indexes': [models.Index(fields=['status', 'created_at'], name='leads_status_3627df_idx'), models.Index(fields=['source'], name='leads_source_805dfa_idx')],
            },
        ),
        migrations.CreateModel(
            name='InteractiveRunModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interactive_definition_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_level', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, null=True)),
                ('result_profile', models.CharField(blank=True, max_length=255, null=True)),
                ('crisis_triggered', models.BooleanField(default=False)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='started', max_length=20)),
            ],
            options={
                'db_table': 'interactive_runs',
                'indexes': [models.Index(fields=['user_id', 'status'], name='interactive_user_id_4962f0_idx'), models.Index(fields=['anonymous_id', 'status'], name='interactive_anonymo_255865_idx'), models.Index(fields=['interactive_definition_id', 'started_at'], name='interactive_interac_f6c433_idx')],
            },
        ),
        migrations.CreateModel(
            name='InteractiveDefinitionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('interactive_type', models.CharField(choices=[('quiz', 'Quiz'), ('navigator', 'Navigator'), ('thermometer', 'Thermometer'), ('boundaries', 'Boundaries Script'), ('prep', 'Prep'), ('ritual', 'Ritual')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('topic_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interactive_definitions',
                'indexes': [models.Index(fields=['interactive_type', 'status'], name='interactive_interac_beceae_idx'), models.Index(fields=['topic_code'], name='interactive_topic_c_f816ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiaryEntryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('diary_type', models.CharField(choices=[('mood', 'Mood'), ('thoughts', 'Thoughts'), ('gratitude', 'Gratitude'), ('reflection', 'Reflection')], max_length=50)),
                ('content_encrypted', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diary_entries',
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='diary_entri_user_id_b30cb5_idx'), models.Index(fields=['diary_type'], name='diary_entri_diary_t_8438df_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeepLinkModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('flow', models.CharField(choices=[('quiz', 'Quiz'), ('booking', 'Booking'), ('content', 'Content'), ('diary', 'Diary')], max_length=50)),
                ('telegram_user_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'deep_links',
                'indexes': [models.Index(fields=['token'], name='deep_links_token_b09392_idx'), models.Index(fields=['expires_at'], name='deep_links_expires_35364d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('export_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF')], default='json', max_length=20)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_export_requests',
                'indexes': [models.Index(fields=['user_id', 'status'], name='data_export_user_id_58dcab_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('audio', 'Audio'), ('exercise', 'Exercise'), ('tool', 'Tool')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('time_to_benefit', models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('short_term', 'Short Term'), ('medium_term', 'Medium Term'), ('long_term', 'Long Term')], max_length=20, null=True)),
                ('content_body', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_items',
                'indexes': [models.Index(fields=['slug'], name='content_ite_slug_4f1fde_idx'), models.Index(fields=['content_type', 'status'], name='content_ite_content_0394d4_idx'), models.Index(fields=['status', 'published_at'], name='content_ite_status_c08066_idx')],
            },
        ),
        # ConsentModel и AuditLogModel уже созданы в 0001_initial
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_id', models.UUIDField(db_index=True)),
                ('client_user_id', models.UUIDField(db_index=True, null=True)),
                ('lead_id', models.UUIDField(blank=True, null=True)),
                ('start_at_utc', models.DateTimeField(db_index=True)),
                ('end_at_utc', models.DateTimeField()),
                ('timezone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('no_show', 'No Show')], db_index=True, default='pending_payment', max_length=50)),
                ('format', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('slot_id', models.UUIDField(blank=True, null=True)),
                ('external_calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_url', models.URLField(blank=True, null=True)),
                ('location_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appointments',
                'indexes': [models.Index(fields=['start_at_utc', 'status'], name='appointment_start_a_021482_idx'), models.Index(fields=['client_user_id', 'status'], name='appointment_client__f277c3_idx'), models.Index(fields=['service_id'], name='appointment_service_8b5966_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='appointmentmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_payment', 'confirmed'])), fields=('start_at_utc',), name='unique_active_appointment_time'),
        ),
        # Индексы для существующих моделей уже созданы в 0001_initial
    ]
