# Generated by Django 6.0.1 on 2026-01-27 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('persistence', '0004_initial_infrastructure_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlotModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('blocked', 'Blocked')], db_index=True, default='available', max_length=20)),
                ('source', models.CharField(choices=[('product', 'Product'), ('google_calendar', 'Google Calendar')], default='product', max_length=50)),
                ('external_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'availability_slots',
            },
        ),
        migrations.CreateModel(
            name='BoundaryScriptModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario', models.CharField(choices=[('work', 'Work'), ('family', 'Family'), ('partner', 'Partner'), ('friends', 'Friends')], db_index=True, max_length=50)),
                ('style', models.CharField(choices=[('soft', 'Soft'), ('brief', 'Brief'), ('firm', 'Firm')], db_index=True, max_length=20)),
                ('goal', models.CharField(choices=[('refuse', 'Refuse'), ('ask', 'Ask'), ('set_rule', 'Set Rule'), ('pause', 'Pause')], db_index=True, max_length=20)),
                ('script_text', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'boundary_scripts',
            },
        ),
        migrations.CreateModel(
            name='WebhookEventModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_payment_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webhook_events',
            },
        ),
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
            ],
        ),
        migrations.RenameIndex(
            model_name='auditlogmodel',
            new_name='audit_log_actor_u_745545_idx',
            old_name='audit_log_actor_user_id_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlogmodel',
            new_name='audit_log_action_b32d4d_idx',
            old_name='audit_log_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlogmodel',
            new_name='audit_log_entity__c2633a_idx',
            old_name='audit_log_entity_type_entity_id_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlogmodel',
            new_name='audit_log_created_5a7975_idx',
            old_name='audit_log_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='consentmodel',
            new_name='consents_user_id_517cf5_idx',
            old_name='consents_user_consent_type_idx',
        ),
        migrations.RenameIndex(
            model_name='consentmodel',
            new_name='consents_granted_702c3f_idx',
            old_name='consents_granted_idx',
        ),
        migrations.RenameIndex(
            model_name='usermodel',
            new_name='users_email_4b85f2_idx',
            old_name='users_email_idx',
        ),
        migrations.RenameIndex(
            model_name='usermodel',
            new_name='users_phone_af6883_idx',
            old_name='users_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='usermodel',
            new_name='users_telegra_613f9c_idx',
            old_name='users_telegram_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='usermodel',
            new_name='users_status_9ca66f_idx',
            old_name='users_status_idx',
        ),
        migrations.RenameIndex(
            model_name='userrolemodel',
            new_name='user_roles_user_id_05df60_idx',
            old_name='user_roles_user_idx',
        ),
        migrations.RenameIndex(
            model_name='userrolemodel',
            new_name='user_roles_role_id_0b583b_idx',
            old_name='user_roles_role_idx',
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='appointment_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.CharField(choices=[('intent', 'Intent'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], db_index=True, default='intent', max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='persistence_user_set', related_query_name='persistence_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='persistence_user_set', related_query_name='persistence_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='availabilityslotmodel',
            index=models.Index(fields=['service_id', 'start_at', 'status'], name='availabilit_service_b5b302_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslotmodel',
            index=models.Index(fields=['start_at', 'end_at'], name='availabilit_start_a_1c2337_idx'),
        ),
        migrations.AddIndex(
            model_name='boundaryscriptmodel',
            index=models.Index(fields=['scenario', 'style', 'goal', 'status'], name='boundary_sc_scenari_9b59ca_idx'),
        ),
        migrations.AddIndex(
            model_name='boundaryscriptmodel',
            index=models.Index(fields=['status', 'display_order'], name='boundary_sc_status_8bc599_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boundaryscriptmodel',
            unique_together={('scenario', 'style', 'goal', 'display_order')},
        ),
        migrations.AddIndex(
            model_name='webhookeventmodel',
            index=models.Index(fields=['provider_payment_id', 'event_type'], name='webhook_eve_provide_54b0ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookeventmodel',
            constraint=models.UniqueConstraint(fields=('provider_payment_id', 'event_type'), name='unique_webhook_event'),
        ),
    ]
